name: GitHub Actions to Build & Deploy
on: push
jobs:
  Build_Actions_Job:
    name: Exploring Building Docker Images
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event"

      - name: Check out bank-app respository
        uses: actions/checkout@v2

      - run: echo "Repository code copied to the ${{ github.workspace }}"

      - name: List repository files
        run: |
          ls ${{ github.workspace }}

      - name: Build and push BankAppBackend Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_ROOT_PATH: 'bank-app-backend'
          DOCKERFILE_PATH: 'BankAppBackend/Dockerfile'
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
        run: |
          cd $PROJECT_ROOT_PATH
          ls -l
          docker build -f $DOCKERFILE_PATH --force-rm -t thebankappcontainer.azurecr.io/bankappbackend .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
      - name: Build and push bank-app-frontend Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_PATH: 'bank-app-frontend/bank-app-frontend'  # Adjust the path to your project
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
        run: |
          cd $PROJECT_PATH
          docker build -t $IMAGE_NAME .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
          
      - name: Build and push BankTrackingSystem Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_PATH: 'BankTrackingSystem'  # Adjust the path to your project
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
        run: |
          cd $PROJECT_PATH
          docker build -t $IMAGE_NAME .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
