name: Build Docker images & Push to Azure Container Registry

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: 'dotnettrainingbankapp'
  FRONTEND_APP_IMAGE_NAME: 'thebankappcontainer.azurecr.io/bankappfrontend:${{ github.sha }}'

jobs:
  Build_Actions_Job:
    name: Build & Push BankAppBackend, BankTrackingSystem, BankAppFrontend
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event"

      - name: Check out bank-app respository
        uses: actions/checkout@v2

      - run: echo "Repository code copied to the ${{ github.workspace }}"

      - name: List repository files
        run: |
          ls ${{ github.workspace }}
      
      # - name: Build and push BankAppBackend Docker image
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     PROJECT_ROOT_PATH: 'bank-app-backend'
      #     DOCKERFILE_PATH: 'BankAppBackend/Dockerfile'
      #     IMAGE_NAME: 'thebankappcontainer.azurecr.io/bankappbackend'
      #   run: |
      #     cd $PROJECT_ROOT_PATH
      #     docker build -f $DOCKERFILE_PATH --force-rm -t $IMAGE_NAME .
      #     docker login thebankappcontainer.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker push $IMAGE_NAME
          
      # - name: Build and push bank-app-frontend Docker image
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     PROJECT_ROOT_PATH: 'bank-app-frontend'
      #     DOCKERFILE_PATH: 'bank-app-frontend/Dockerfile'
      #   run: |
      #     cd $PROJECT_ROOT_PATH          
      #     docker build -f $DOCKERFILE_PATH --force-rm -t ${{ env.FRONTEND_APP_IMAGE_NAME }} .
      #     docker login thebankappcontainer.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker push ${{ env.FRONTEND_APP_IMAGE_NAME }}
          
      # - name: Build and push BankTrackingSystem Docker image
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     PROJECT_ROOT_PATH: 'BankTrackingSystem'
      #     DOCKERFILE_PATH: 'Dockerfile'
      #     IMAGE_NAME: 'thebankappcontainer.azurecr.io/banktrackingsystem:${{ github.sha }}'
      #   run: |
      #     cd $PROJECT_ROOT_PATH
      #     docker build -f $DOCKERFILE_PATH --force-rm -t $IMAGE_NAME .
      #     docker login thebankappcontainer.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker push $IMAGE_NAME

      # - name: Build and push TestMVCApp
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     # cd 'TestMVCApp'
      #     ls -l
      #     docker build -f 'TestMVCApp/Dockerfile' --force-rm -t thebankappcontainer.azurecr.io/testmvcapp:${{ github.sha }} .
      #     docker login thebankappcontainer.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #     docker push thebankappcontainer.azurecr.io/testmvcapp:${{ github.sha }}

      # - name: Deploy to Azure App Service
      #   uses: Azure/webapps-deploy@v3.0.0
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.azureWebAppPublishProfileProduction }}
      #     images: ${{ env.FRONTEND_APP_IMAGE_NAME }}
      #     restart: true
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Azure CLI Script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
