name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

 build-and-push:
    runs-on: ubuntu-latest

    steps:
     
 # Build and push Docker images for each project
    - name: Build and push BankAppBackend Docker image
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_PATH: 'bank-app-backend/BankAppBackend/Dockerfile'  # Adjust the path to your project
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
      run: |
          cd $PROJECT_PATH
          docker build -t $PROJECT_PATH
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
    - name: Build and push bank-app-frontend Docker image
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_PATH: 'bank-app-frontend/bank-app-frontend'  # Adjust the path to your project
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
      run: |
          cd $PROJECT_PATH
          docker build -t $PROJECT_PATH
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
          
    - name: Build and push BankTrackingSystem Docker image
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          PROJECT_PATH: 'BankTrackingSystem'  # Adjust the path to your project
          IMAGE_NAME: 'thebankappcontainer.azurecr.io'
      run: |
          cd $PROJECT_PATH
          docker build -t $PROJECT_PATH
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $IMAGE_NAME
